# Generated by Django 5.1.3 on 2024-11-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('emailId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('custname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('contact_No', models.BigIntegerField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
